services:
    mariadb:
        container_name: mariadb
        build: /home/achu/inception/srcs/requirements/mariadb
        env_file:
          - .env
        volumes:
          - mariadb:/var/lib/mysql
        networks:
          - inception
        expose:
        - "3306"
        restart: always
    wordpress:
        container_name: wordpress
        build: /home/achu/inception/srcs/requirements/wordpress
        env_file:
          - .env
        depends_on:
          - mariadb
        volumes:
          - wordpress:/var/www/html
        networks:
          - inception
        expose:
        - "9000"
        restart: always
    nginx:
        container_name: nginx
        build: /home/achu/inception/srcs/requirements/nginx
        env_file:
          - .env
        depends_on:
          - wordpress
        volumes:
         - wordpress:/var/www/html
        networks:
          - inception
        ports:
        - "443:443"
        restart: always

volumes:
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            type: none
            device: /home/achu/data/mysql
            o: bind
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            type: none
            device: /home/achu/data/wordpress
            o: bind

networks:
    inception:
        name: inception
        driver: bridge

